"use client";

import { useEffect, useMemo, useState } from "react";
import { calculatePaidSocialOpportunity } from "@/lib/paid-social";
import type { MarketCode } from "@/lib/arbitra";
import { MARKETS, MARKET_BY_CODE } from "@/lib/markets";

type TargetMarket = "GLOBAL" | MarketCode;
type View = "opportunities" | "intelligence" | "allocate" | "sources";
type SourceStatus = { mode:"demo"|"partial"|"live-ready"; connected:number; totalSignalGroups:number; persistence:boolean; sources:Record<string,{configured:boolean;role:string}>; note:string };
type Opportunity = { name:string; category:string; demand:number; confidence:number; metaAds:number; advertisers:number; tiktok:number; competition:number; margin:number; upstream:string[]; window:string };

const seeds:Opportunity[]=[
{name:"Portable Cold Plunge",category:"Fitness & Recovery",demand:82,confidence:79,metaAds:11,advertisers:4,tiktok:88,competition:24,margin:67,upstream:["US","UK","DE"],window:"12–27d"},
{name:"Walking Pad",category:"Home Fitness",demand:76,confidence:83,metaAds:24,advertisers:9,tiktok:79,competition:38,margin:54,upstream:["US","DE","UK"],window:"8–21d"},
{name:"LED Scalp Massager",category:"Beauty",demand:71,confidence:68,metaAds:7,advertisers:3,tiktok:91,competition:18,margin:72,upstream:["US","UK","JP"],window:"14–32d"},
{name:"Mini Thermal Printer",category:"Electronics",demand:63,confidence:74,metaAds:42,advertisers:16,tiktok:64,competition:57,margin:46,upstream:["US","JP","DE"],window:"21–40d"}];
const clamp=(v:number)=>Math.max(0,Math.min(100,Math.round(v)));
function scoreOpportunity(p:Opportunity,index:number,market:MarketCode){const marketDef=MARKET_BY_CODE[market],factor=marketDef.demoFactor,demand=clamp(p.demand*factor-index*1.2),tiktok=clamp(p.tiktok*(.92+factor*.08)),metaAds=Math.max(1,Math.round(p.metaAds*(.7+factor*.3))),advertisers=Math.max(1,Math.round(p.advertisers*(.75+factor*.25))),competition=clamp(p.competition*(.85+factor*.15));const paid=calculatePaidSocialOpportunity({demandProbability:demand,meta:marketDef.meta?{source:"meta",market,observedAt:"demo",activeAds:metaAds,uniqueAdvertisers:advertisers,confidence:.8}:undefined,tiktok:marketDef.tiktok?{source:"tiktok",market,observedAt:"demo",trendVelocity:tiktok,creatorGrowth:tiktok-8,engagementVelocity:tiktok+4,confidence:.8}:undefined,marketplaceCompetition:competition,marginPercent:p.margin});const sourceCount=[marketDef.google,marketDef.meta,marketDef.tiktok,marketDef.marketplaces.length>0].filter(Boolean).length,globalScore=clamp(paid.score-(4-sourceCount)*3),route=[...p.upstream.filter(m=>m!==market).slice(0,3),market].join(" → ");return {...p,market,marketDef,demand,tiktok,metaAds,advertisers,competition,paid:{...paid,score:globalScore},route,sourceCount}}

export default function Home(){
const [target,setTarget]=useState<TargetMarket>("GLOBAL"),[view,setView]=useState<View>("opportunities"),[runtime,setRuntime]=useState<SourceStatus|null>(null),[budget,setBudget]=useState(5000);const isGlobal=target==="GLOBAL";
useEffect(()=>{fetch("/api/system-status",{cache:"no-store"}).then(r=>r.json()).then(setRuntime).catch(()=>setRuntime(null))},[]);
const allRows=useMemo(()=>MARKETS.flatMap(m=>seeds.map((p,i)=>scoreOpportunity(p,i,m.code))).sort((a,b)=>b.paid.score-a.paid.score),[]),rows=useMemo(()=>isGlobal?allRows.slice(0,12):allRows.filter(r=>r.market===target).slice(0,8),[allRows,isGlobal,target]),top=rows[0];
const allocation=useMemo(()=>{const candidates=allRows.filter(r=>r.paid.score>=65).slice(0,4),weights=candidates.map(r=>Math.max(1,r.paid.score-55)),sum=weights.reduce((a,b)=>a+b,0);return candidates.map((r,i)=>{const amount=Math.round((budget*weights[i]/sum)/50)*50;const channel=r.marketDef.tiktok&&r.tiktok>=85?"TikTok Ads":r.marketDef.meta?"Meta Ads":"Paid Social";return {...r,amount,channel,share:Math.round(weights[i]/sum*100)}})},[allRows,budget]);
const runtimeLabel=runtime?.mode==="live-ready"?"LIVE READY":runtime?.mode==="partial"?"PARTIAL DATA":"DEMO MODE";
return <main className="shell"><header className="topbar"><div><div className="brand">ARBITRA TERMINAL</div><div className="subtitle">Global Product Intelligence · Discover → Validate → Allocate → Monitor.</div></div><div className="headerRight"><span className={runtime?.mode==="live-ready"?"liveDot":"liveDot demoDot"}/>{runtimeLabel}<span className="badge">ENGINE v0.6</span></div></header>
<section className="navRow"><div className="viewTabs">{[["opportunities","Discover"],["intelligence","Validate"],["allocate","Allocate"],["sources","Sources"]].map(([k,l])=><button key={k} className={view===k?"viewTab active":"viewTab"} onClick={()=>setView(k as View)}>{l}{k==="sources"&&<span className="tabCount"> {runtime?.connected??0}/4</span>}</button>)}</div><div className="modeNote">PRODUCT × MARKET × CHANNEL</div></section>
<section className="marketStrip"><span className="marketStripLabel">MARKET</span><div className="marketTabs"><button className={isGlobal?"marketTab active":"marketTab"} onClick={()=>setTarget("GLOBAL")}>🌐 GLOBAL</button>{MARKETS.map(m=><button key={m.code} className={m.code===target?"marketTab active":"marketTab"} onClick={()=>setTarget(m.code)}>{m.flag} {m.code}</button>)}</div></section>
<section className="controlBar"><div><span className="muted">TARGET</span><div className="selectWrap"><select value={target} onChange={e=>setTarget(e.target.value as TargetMarket)}><option value="GLOBAL">🌐 Global · Best market automatically</option>{MARKETS.map(m=><option key={m.code} value={m.code}>{m.flag} {m.name}</option>)}</select></div></div><div><span className="muted">DECISION ENGINE</span><strong>{isGlobal?"PRODUCT × COUNTRY × CHANNEL":"LOCAL MARKET ENTRY"}</strong></div><div><span className="muted">DATA</span><strong>{runtime?`${runtime.connected}/4 SIGNAL GROUPS${runtime.persistence?" · DB ON":" · DB PENDING"}`:"CHECKING…"}</strong></div></section>
{view==="opportunities"&&<><section className="hero compactHero"><div className="metric featured"><div className="label">#1 Opportunity</div><div className="value nameValue">{top.name}</div><div className="micro">{top.marketDef.flag} {top.marketDef.name} · {top.category}</div></div><div className="metric"><div className="label">Opportunity</div><div className="value accent">{top.paid.score}</div><div className="micro">{top.paid.status}</div></div><div className="metric"><div className="label">Best Channel</div><div className="value nameValue">{top.marketDef.tiktok&&top.tiktok>=85?"TikTok Ads":"Meta Ads"}</div><div className="micro">demo recommendation</div></div><div className="metric"><div className="label">Entry Window</div><div className="value">{top.window}</div><div className="micro">{top.marketDef.name}</div></div></section><section className="panel opportunityPanel"><div className="panelTitle"><div><h2>{isGlobal?"INVESTMENT OPPORTUNITIES":`OPPORTUNITIES · ${top.marketDef.name.toUpperCase()}`}</h2><p>Ranked product-market opportunities for paid-social testing.</p></div><button className="primaryAction" onClick={()=>setView("allocate")}>ALLOCATE BUDGET →</button></div><div className="tableWrap"><table className="table terminalTable"><thead><tr><th>#</th><th>Product</th>{isGlobal&&<th>Market</th>}<th>Demand</th><th>Competition</th><th>Margin</th><th>Channel</th><th>Score</th><th>Decision</th></tr></thead><tbody>{rows.map((p,i)=><tr key={`${p.name}-${p.market}`} onClick={()=>{setTarget(p.market);setView("intelligence")}}><td>{String(i+1).padStart(2,"0")}</td><td><strong>{p.name}</strong><span className="cellSub">{p.category}</span></td>{isGlobal&&<td>{p.marketDef.flag} {p.market}</td>}<td>{p.demand}%</td><td>{p.competition}</td><td>{p.margin}%</td><td>{p.marketDef.tiktok&&p.tiktok>=85?"TikTok":"Meta"}</td><td><strong className="score">{p.paid.score}</strong></td><td><span className={`signal ${p.paid.status.replaceAll(" ","").toLowerCase()}`}>{p.paid.status}</span></td></tr>)}</tbody></table></div></section></>}
{view==="intelligence"&&<section className="grid intelligenceGrid"><div className="panel"><div className="eyebrow">VALIDATE OPPORTUNITY</div><h1 className="detailTitle">{top.name} <span>{top.marketDef.flag} {top.marketDef.name}</span></h1><div className="route bigRoute">{top.route.split(" → ").map((m,i,a)=><span key={`${m}-${i}`} className="routePart"><span className={`node ${i===a.length-1?"target":""}`}>{m}<small>{i===0?"BREAKOUT":i===a.length-1?"TARGET / EARLY":"ACCELERATING"}</small></span>{i<a.length-1&&<span className="arrow">→</span>}</span>)}</div><div className="intel"><div><span>Demand</span><b>{top.demand}%</b></div><div><span>TikTok</span><b>{top.marketDef.tiktok?`${top.tiktok}/100`:"—"}</b></div><div><span>Meta saturation</span><b>{top.marketDef.meta?`${top.paid.metaSaturation}/100`:"—"}</b></div><div><span>Competition</span><b>{top.competition}/100</b></div></div></div><aside className="panel actionPanel"><div className="eyebrow">DECISION</div><div className="actionLabel">{top.paid.status}</div><div className="actionScore">{top.paid.score}<small>/100</small></div><p>Suggested channel: <strong>{top.marketDef.tiktok&&top.tiktok>=85?"TikTok Ads":"Meta Ads"}</strong>. This becomes actionable only after live data validation.</p><button className="primaryAction wide" onClick={()=>setView("allocate")}>ADD TO BUDGET PLAN →</button></aside></section>}
{view==="allocate"&&<section className="allocationLayout"><div className="panel allocationHead"><div><div className="eyebrow">AD BUDGET ALLOCATOR</div><h1 className="detailTitle">Where should the next euro be tested?</h1><p className="mutedText">ARBITRA distributes a test budget over the strongest product × country × channel combinations. Demo planning only until live signals are validated.</p></div><label className="budgetInput"><span>TEST BUDGET</span><div>€ <input type="number" min="500" step="500" value={budget} onChange={e=>setBudget(Math.max(0,Number(e.target.value)))}/></div></label></div><div className="allocationGrid">{allocation.map((p,i)=><div className="panel allocationCard" key={`${p.name}-${p.market}`}><div className="allocationRank">0{i+1}</div><div className="eyebrow">{p.marketDef.flag} {p.marketDef.name}</div><h3>{p.name}</h3><div className="channelPill">{p.channel}</div><div className="allocationAmount">€{p.amount.toLocaleString("nl-NL")}</div><div className="allocationShare">{p.share}% of test budget</div><div className="miniMetrics"><span>Score <b>{p.paid.score}</b></span><span>Demand <b>{p.demand}%</b></span><span>Competition <b>{p.competition}</b></span></div></div>)}</div><div className="panel guardrail"><strong>Allocation guardrail</strong><p>This is a decision-support plan, not a promise of return. Once live Meta/TikTok and outcome data are connected, allocations should be capped by confidence, data coverage, margin, CPA/ROAS targets and actual test results.</p></div></section>}
{view==="sources"&&<section className="sourcesLayout"><div className="panel sourceSummary"><div className="eyebrow">SYSTEM READINESS</div><div className="readinessNumber">{runtime?.connected??0}<small>/4</small></div><h2>SIGNAL GROUPS CONFIGURED</h2></div><div className="sourceGrid">{[["Google","google","Demand formation"],["Meta","meta","Ad saturation"],["TikTok","tiktok","Creative acceleration"],["bol.com","bol","NL/BE marketplace"],["Amazon","amazon","Global marketplace"]].map(([label,key,role])=>{const configured=runtime?.sources?.[key]?.configured??false;return <div className="panel sourceCard" key={key}><div className="sourceCardTop"><strong>{label}</strong><span className={configured?"sourceState ready":"sourceState pending"}>{configured?"CONFIGURED":"NEEDS SETUP"}</span></div><p>{role}</p></div>})}</div></section>}
<footer className="footer terminalFooter"><strong>DATA NOTICE</strong> · Current rankings, channel recommendations and allocations use demo/model seed data. Do not deploy ad spend from these figures until live observations and historical validation are connected.</footer></main>}
