"use client";

import { useEffect, useMemo, useState } from "react";
import { MARKETS, MARKET_BY_CODE } from "@/lib/markets";
import type { MarketCode } from "@/lib/arbitra";

type View="radar"|"opportunity"|"tests"|"research"|"sources";
type Stage="EARLY SIGNAL"|"EMERGING"|"BREAKOUT CANDIDATE"|"ENTRY WINDOW";
type SourceStatus={mode:"demo"|"partial"|"live-ready";connected:number;persistence:boolean;sources:Record<string,{configured:boolean}>};
type Seed={name:string;category:string;origin:MarketCode;stage:Stage;confidence:number;demand:number;acceleration:number;saturation:number;brand:number;window:string;route:MarketCode[];signals:string[];thesis:string};

const seeds:Seed[]=[
{name:"Portable Cold Plunge",category:"Fitness & Recovery",origin:"US",stage:"ENTRY WINDOW",confidence:82,demand:84,acceleration:88,saturation:27,brand:74,window:"12–27 days",route:["US","UK","DE","NL"],signals:["Search acceleration","Creator velocity","Geographic spread","Low advertiser saturation"],thesis:"Demand is accelerating across leading markets while local commercial saturation still trails the demand signal."},
{name:"LED Scalp Massager",category:"Beauty",origin:"JP",stage:"BREAKOUT CANDIDATE",confidence:76,demand:78,acceleration:91,saturation:19,brand:81,window:"14–32 days",route:["JP","US","UK","DE"],signals:["Creator acceleration","Search lift","Low seller density","High margin potential"],thesis:"Social acceleration is leading search demand and the next-market pattern remains relatively uncrowded."},
{name:"Walking Pad",category:"Home Fitness",origin:"US",stage:"EMERGING",confidence:72,demand:75,acceleration:73,saturation:46,brand:77,window:"8–21 days",route:["US","DE","UK","FR"],signals:["Cross-market search","Marketplace adoption","Review velocity"],thesis:"Demand is established but saturation is rising; remaining value depends on finding lagging markets."},
{name:"Mini Thermal Printer",category:"Electronics",origin:"JP",stage:"EARLY SIGNAL",confidence:61,demand:62,acceleration:69,saturation:54,brand:48,window:"21–40 days",route:["JP","US","DE","ES"],signals:["Search velocity","Social mentions"],thesis:"Early movement exists, but evidence is not yet strong enough for a high-confidence commercial entry call."}
];
const score=(s:Seed,m:MarketCode)=>{const f=MARKET_BY_CODE[m].demoFactor;return Math.max(0,Math.min(100,Math.round(s.demand*.34+s.acceleration*.28+(100-s.saturation)*.22+s.confidence*.16+(f-1)*18)))};

export default function Home(){
 const [view,setView]=useState<View>("radar"),[selected,setSelected]=useState(0),[market,setMarket]=useState<"GLOBAL"|MarketCode>("GLOBAL"),[runtime,setRuntime]=useState<SourceStatus|null>(null);
 useEffect(()=>{fetch("/api/system-status",{cache:"no-store"}).then(r=>r.json()).then(setRuntime).catch(()=>null)},[]);
 const opportunities=useMemo(()=>seeds.flatMap((s,si)=>MARKETS.map(m=>({s,si,m,score:score(s,m.code)}))).filter(x=>market==="GLOBAL"||x.m.code===market).sort((a,b)=>b.score-a.score).slice(0,10),[market]);
 const active=opportunities[selected]??opportunities[0];
 const status=runtime?.mode==="live-ready"?"LIVE READY":runtime?.mode==="partial"?"PARTIAL DATA":"DEMO / VALIDATION MODE";
 return <main className="shell">
  <header className="topbar"><div><div className="brand">ARBITRA TERMINAL</div><div className="subtitle">Global Product Intelligence · detect commercial windows before they become obvious.</div></div><div className="headerRight"><span className={runtime?.mode==="live-ready"?"liveDot":"liveDot demoDot"}/>{status}<span className="badge">RADAR v0.7</span></div></header>
  <nav className="navRow"><div className="viewTabs">{[["radar","Opportunity Radar"],["opportunity","Deep Dive"],["tests","Test & Scale"],["research","Research"],["sources","Sources"]].map(([k,l])=><button key={k} className={view===k?"viewTab active":"viewTab"} onClick={()=>setView(k as View)}>{l}</button>)}</div><div className="modeNote">PRODUCT × MARKET × TIMING</div></nav>
  <section className="marketStrip"><span className="marketStripLabel">RADAR SCOPE</span><div className="marketTabs"><button className={market==="GLOBAL"?"marketTab active":"marketTab"} onClick={()=>{setMarket("GLOBAL");setSelected(0)}}>🌐 WORLDWIDE</button>{MARKETS.map(m=><button key={m.code} className={market===m.code?"marketTab active":"marketTab"} onClick={()=>{setMarket(m.code);setSelected(0)}}>{m.flag} {m.code}</button>)}</div></section>

  {view==="radar"&&<><section className="radarHero"><div><div className="eyebrow">GLOBAL OPPORTUNITY RADAR</div><h1>What is emerging <em>before</em> it becomes obvious?</h1><p>ARBITRA ranks product × market entry windows by demand acceleration, geographic propagation, saturation and confidence. The intelligence layer is being validated on historical data.</p></div><div className="radarStats"><div><b>{opportunities.length}</b><span>TOP WINDOWS</span></div><div><b>{MARKETS.length}</b><span>MARKETS</span></div><div><b>{runtime?.connected??0}/4</b><span>LIVE SIGNAL GROUPS</span></div></div></section>
  <section className="stageRail">{["EARLY SIGNAL","EMERGING","BREAKOUT CANDIDATE","ENTRY WINDOW"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><small>{i===0?"weak but unusual movement":i===1?"multiple signals confirm":i===2?"historical pattern forming":"commercial timing looks attractive"}</small></div>)}</section>
  <section className="panel opportunityPanel"><div className="panelTitle"><div><h2>RANKED ENTRY WINDOWS</h2><p>Not “winning products”: markets where demand may be moving faster than saturation.</p></div></div><div className="tableWrap"><table className="table terminalTable"><thead><tr><th>#</th><th>Opportunity</th><th>Market</th><th>Phase</th><th>Demand</th><th>Acceleration</th><th>Saturation</th><th>Confidence</th><th>Radar score</th></tr></thead><tbody>{opportunities.map((o,i)=><tr key={`${o.s.name}-${o.m.code}`} onClick={()=>{setSelected(i);setView("opportunity")}}><td>{String(i+1).padStart(2,"0")}</td><td><strong>{o.s.name}</strong><span className="cellSub">{o.s.category}</span></td><td>{o.m.flag} {o.m.code}</td><td><span className="phase">{o.s.stage}</span></td><td>{o.s.demand}%</td><td className="positive">↑ {o.s.acceleration}</td><td>{o.s.saturation}</td><td>{o.s.confidence}%</td><td><strong className="score">{o.score}</strong></td></tr>)}</tbody></table></div></section></>}

  {view==="opportunity"&&active&&<section className="deepGrid"><div className="panel"><div className="eyebrow">OPPORTUNITY THESIS</div><h1 className="detailTitle">{active.s.name} <span>{active.m.flag} {active.m.name}</span></h1><div className="decisionRow"><span className="phase large">{active.s.stage}</span><strong>{active.score}<small>/100 RADAR</small></strong></div><p className="thesis">{active.s.thesis}</p><h2>WHY ARBITRA DETECTED IT</h2><div className="signalGrid">{active.s.signals.map(x=><div key={x}>↗ <b>{x}</b><small>signal awaiting live calibration</small></div>)}</div><h2>GEOGRAPHIC PROPAGATION</h2><div className="route bigRoute">{active.s.route.map((r,i)=><span className="routePart" key={r}><span className={`node ${r===active.m.code?"target":""}`}>{r}<small>{i===0?"ORIGIN":i===active.s.route.length-1?"NEXT":"EXPANDING"}</small></span>{i<active.s.route.length-1&&<span className="arrow">→</span>}</span>)}</div></div><aside className="panel evidence"><div className="eyebrow">DECISION SUPPORT</div><div className="evidenceMetric"><span>ENTRY WINDOW</span><b>{active.s.window}</b></div><div className="evidenceMetric"><span>CONFIDENCE</span><b>{active.s.confidence}%</b></div><div className="evidenceMetric"><span>SATURATION</span><b>{active.s.saturation}/100</b></div><div className="evidenceMetric"><span>BRAND POTENTIAL</span><b>{active.s.brand}/100</b></div><button className="primaryAction wide" onClick={()=>setView("tests")}>BUILD TEST PLAN →</button><p className="warning">Demo evidence until historical backtesting and live sources validate the signal.</p></aside></section>}

  {view==="tests"&&<section className="panel emptyState"><div className="eyebrow">TEST → VALIDATE → SCALE → BRAND</div><h1>Turn an opportunity into a controlled experiment.</h1><p>This workspace will track test spend, CPA/ROAS, margin, kill/scale criteria and the next geographic expansion window. It becomes actionable after live ad/outcome integrations are connected.</p><div className="flow"><b>OPPORTUNITY</b><span>→</span><b>TEST</b><span>→</span><b>VALIDATE</b><span>→</span><b>SCALE</b><span>→</span><b>BRAND</b></div></section>}

  {view==="research"&&<section className="panel emptyState"><div className="eyebrow">POWER USER RESEARCH</div><h1>Evidence behind the recommendation.</h1><p>Search, social, creator, ad, marketplace, pricing and supply signals live here. Research supports the decision; it is not the primary product experience.</p></section>}

  {view==="sources"&&<section className="sourcesLayout"><div className="panel sourceSummary"><div className="eyebrow">INTELLIGENCE COVERAGE</div><div className="readinessNumber">{runtime?.connected??0}<small>/4</small></div><h2>LIVE SIGNAL GROUPS CONFIGURED</h2></div><div className="sourceGrid">{[["Google","google","Search demand + historical backtests"],["Meta","meta","Advertiser saturation"],["TikTok","tiktok","Social / creative acceleration"],["bol.com","bol","Marketplace demand & supply"],["Amazon","amazon","Global marketplace validation"]].map(([label,key,role])=>{const ok=runtime?.sources?.[key]?.configured??false;return <div className="panel sourceCard" key={key}><div className="sourceCardTop"><strong>{label}</strong><span className={ok?"sourceState ready":"sourceState pending"}>{ok?"CONFIGURED":"NEEDS SETUP"}</span></div><p>{role}</p></div>})}</div></section>}
  <footer className="footer terminalFooter"><strong>VALIDATION NOTICE</strong> · Current opportunities are illustrative model seeds, not live recommendations. The next milestone is historical walk-forward validation against real data before any commercial decision should rely on these scores.</footer>
 </main>
}
